/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VerifyPIIInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "VerifyMessage"
      | "getEthSignedMessageHashV1"
      | "getMessageHashV1"
      | "getSignerAddressFromSignatureV1"
      | "recoverSigner"
      | "retrieve"
      | "splitSignature"
      | "store"
      | "verifySignatureV1"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "VerifyMessage",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthSignedMessageHashV1",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageHashV1",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignerAddressFromSignatureV1",
    values: [string, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverSigner",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "retrieve", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "splitSignature",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "store", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "verifySignatureV1",
    values: [string, string, string, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "VerifyMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthSignedMessageHashV1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageHashV1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignerAddressFromSignatureV1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "retrieve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "splitSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "store", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySignatureV1",
    data: BytesLike
  ): Result;
}

export interface VerifyPII extends BaseContract {
  connect(runner?: ContractRunner | null): VerifyPII;
  waitForDeployment(): Promise<this>;

  interface: VerifyPIIInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  VerifyMessage: TypedContractMethod<
    [_hashedMessage: BytesLike, _v: BigNumberish, _r: BytesLike, _s: BytesLike],
    [string],
    "view"
  >;

  getEthSignedMessageHashV1: TypedContractMethod<
    [_messageHash: BytesLike],
    [string],
    "view"
  >;

  getMessageHashV1: TypedContractMethod<
    [_firstname: string, _lastname: string, _country: string],
    [string],
    "view"
  >;

  getSignerAddressFromSignatureV1: TypedContractMethod<
    [
      _firstname: string,
      _lastname: string,
      _country: string,
      signature: BytesLike
    ],
    [string],
    "view"
  >;

  recoverSigner: TypedContractMethod<
    [_ethSignedMessageHash: BytesLike, _signature: BytesLike],
    [string],
    "view"
  >;

  retrieve: TypedContractMethod<[], [bigint], "view">;

  splitSignature: TypedContractMethod<
    [sig: BytesLike],
    [[string, string, bigint] & { r: string; s: string; v: bigint }],
    "view"
  >;

  store: TypedContractMethod<[num: BigNumberish], [void], "nonpayable">;

  verifySignatureV1: TypedContractMethod<
    [
      _firstname: string,
      _lastname: string,
      _country: string,
      signature: BytesLike,
      _signer: AddressLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "VerifyMessage"
  ): TypedContractMethod<
    [_hashedMessage: BytesLike, _v: BigNumberish, _r: BytesLike, _s: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEthSignedMessageHashV1"
  ): TypedContractMethod<[_messageHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMessageHashV1"
  ): TypedContractMethod<
    [_firstname: string, _lastname: string, _country: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSignerAddressFromSignatureV1"
  ): TypedContractMethod<
    [
      _firstname: string,
      _lastname: string,
      _country: string,
      signature: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "recoverSigner"
  ): TypedContractMethod<
    [_ethSignedMessageHash: BytesLike, _signature: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "retrieve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "splitSignature"
  ): TypedContractMethod<
    [sig: BytesLike],
    [[string, string, bigint] & { r: string; s: string; v: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "store"
  ): TypedContractMethod<[num: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifySignatureV1"
  ): TypedContractMethod<
    [
      _firstname: string,
      _lastname: string,
      _country: string,
      signature: BytesLike,
      _signer: AddressLike
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
