/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as didSol from "./did.sol";
export type { didSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { VerifyPII } from "./did.sol/VerifyPII";
export { VerifyPII__factory } from "./factories/did.sol/VerifyPII__factory";
export { Lock__factory } from "./factories/Lock__factory";
